spring:
  profiles:
    active: DbRandomPopulation
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: SA
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        generate_statistics: true
        cache:
          use_second_level_cache: true
          #use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 568593949275-lrg41604loib2nhqbju58bha470ja32r.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://localhost:8080/auth/oauth2/callback
app:
  security:
    accessTokenExpiryTimeMs: 600000
    refreshTokenExpiryTimeMs: 15778800000
    secret: secret_should_be_in_a_vault
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui
management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: "prometheus"
  endpoint:
    health:
      #show-details: ALWAYS
    info:
  server:
    port: 8080
logging:
  level:
    org:
      hibernate:
        type: trace
